Repository haron-lee/we-wear-weather, pull requests merged in 2023-08, with the labels that each got.

#20 권한요청 페이지
  src/Assets/icon.svg
  src/Assets/location.svg
  src/Atom/userLocationAtom.ts
  src/Components/Permission/RejectionModal.tsx
  src/Components/style/SModal.tsx
  src/Pages/Permission.tsx
  src/Router/Router.tsx
Labels: 🛠️ Feature

#22 ♻️Refactor: interface type 수정
  src/Components/Login/ButtonAge.tsx
  src/Components/Login/ButtonAgeList.tsx
  src/Components/Login/ButtonGender.tsx
  src/Components/Login/ButtonGenderList.tsx
Labels: 🛠️ Feature

#23 ♻️Refactor: weather mock data 따로 분리
  src/Components/Search/CardRain.tsx
  src/Components/Search/CardWave.tsx
  src/Components/Search/CardWaveList.tsx
  src/Components/Search/CardWeather.tsx
  src/Components/Weekly/WeeklyForecast.tsx
  src/Components/common/smallWeatherIcons.ts
  src/GlobalStyle.tsx
  src/Mock/weather.ts
  src/Pages/Search.tsx
Labels: documentation, 🛠️ Feature, 💅 Design

#27 🙈Chore: react query, axios 라이브러리 설치 (#26)
  package-lock.json
  package.json
  src/API/weatherLatLonAPI.ts
  src/App.tsx
  src/Components/Search/CardWaveList.tsx
  src/Components/Search/CardWeather.tsx
  src/Components/common/smallWeatherIcons.ts
  src/Components/common/useWeatherIcon.tsx
  src/Mock/weather.ts
Labels: 🛠️ Feature

#31 주간예보 기능
  public/index.html
  src/API/openWeatherAPI_Config.ts
  src/API/useOpenWeatherAPI.tsx
  src/App.tsx
  src/Components/Weekly/WeeklyForecast.tsx
  src/Pages/Home.tsx
  src/Utils/filterMinMax.ts
  src/Utils/formatDateTime.ts
  src/types/weeklyType.ts
Labels: ✨ Feature

#33 ♻️Refactor: 검색기록 현재 위치 데이터 cityAtom 0번째 인덱스로 변경
  src/API/LoatLonAPI.tsx
  src/API/cityNameAPI.tsx
  src/API/openWeatherAPI_Config.ts
  src/API/weatherLatLonAPI.ts
  src/Atom/userLocationAtom.ts
  src/Components/Permission/RejectionModal.tsx
  src/Components/Search/CardWaveList.tsx
  src/Components/Search/CityWeatherCard.tsx
  src/Components/common/Button.tsx
  src/Hooks/useSearchedCites.tsx
  src/Pages/Permission.tsx
  src/types/cityWeatherType.ts
Labels: ♻️ Refactor

#41 주간날씨
  src/Components/Weekly/WeeklyForecast.tsx
  src/Components/Weekly/WeeklyItem.tsx
  src/Components/common/useWeatherIcon.tsx
  src/Utils/changeDate.ts
  src/Utils/iconDesc.ts
  src/types/weeklyType.ts
Labels: ✨ Feature

#42 :sparkles: Feat & Fix: 세팅페이지 프로필 수정 연동 & 캐릭터 위치 버그 수정
  src/Components/Home/Character.tsx
  src/Components/Home/ParticulateMatter.tsx
  src/Components/Home/SpeechBubble.tsx
  src/Components/Setting/SetAlarmLocation.tsx
  src/Components/Setting/SetProfile.tsx
  src/Components/common/useWeatherIcon.tsx
  src/Pages/Login.tsx
Labels: ✨ Feature

#45 Feat & Fix : 메인페이지 및 설정페이지 성별 및 나이 동기화 수정
  src/API/useOpenWeatherAPI.tsx
  src/Components/Home/SpeechBubble.tsx
  src/Components/Login/ButtonAgeList.tsx
  src/Components/Login/ButtonGenderList.tsx
  src/Components/Setting/SetProfile.tsx
  src/Components/common/useWeatherIcon.tsx
  src/Pages/Login.tsx
  src/Pages/Permission.tsx
  src/Router/Router.tsx
Labels: ✨ Feature

#46 주간날씨, 시간대별 날씨, package.json
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/Components/Home/HourlyForecast.tsx
  src/Components/Weekly/WeeklyForecast.tsx
  src/Hooks/useForecastData.tsx
  src/Utils/changeHour.ts
  src/types/weeklyType.ts
Labels: ✨ Feature

#49 ✨Feat: 서버에서 날씨 api를 업데이트 시킨 시간 노출 및 그 시간에 따른 날씨 카드 시간대 업데이트
  src/API/useOpenWeatherAPI.tsx
  src/Atom/updateDate.ts
  src/Components/Home/SpeechBubble.tsx
  src/Components/Search/CardWeather.tsx
  src/Components/Search/CityWeatherCard.tsx
  src/Components/common/useWeatherIcon.tsx
  src/Pages/Home.tsx
Labels: ✨ Feature

#52 Fix: 주간날씨 날짜바꿔주는 함수 이전날짜 제외해주기
  src/Utils/changeDate.ts
Labels: 🛠️Fix

#54 Design: 메인, 바텀내비
  src/Components/common/BottomNav.tsx
  src/Components/style/SLayout.tsx
  src/Pages/Home.tsx
Labels: 💅 Design

#55 Feat: 체감온도추가
  src/Components/Home/SpeechBubble.tsx
  src/Components/Home/SpeechBubbleWeatherInfo.tsx
Labels: ✨ Feature, 🛠️Fix

#56 Refactor: cloudes 날씨 description 수정
  src/Components/Search/CardWeather.tsx
  src/Components/Search/CityWeatherCard.tsx
  src/Components/common/useWeatherIcon.tsx
Labels: ♻️ Refactor
