Repository haron-lee/we-wear-weather, pull requests merged in 2023-09, with the labels that each got.

#57 Feat: 말풍선 내의 멘트 업데이트 및 캐릭터 업데이트
  src/Assets/characters/female/fall-winter.png
  src/Assets/characters/female/fall.png
  src/Assets/characters/female/spring-fall.png
  src/Assets/characters/female/spring-summer.png
  src/Assets/characters/female/spring.png
  src/Assets/characters/female/summer-fall.png
  src/Assets/characters/female/summer.png
  src/Assets/characters/female/training.png
  src/Assets/characters/male/fall-winter.png
  src/Assets/characters/male/fall.png
  src/Assets/characters/male/spring-fall.png
  src/Assets/characters/male/spring-summer.png
  src/Assets/characters/male/spring.png
  src/Assets/characters/male/summer-fall.png
  src/Assets/characters/male/summer.png
  src/Assets/characters/male/training.png
  src/Atom/mainWeatherAtom.ts
  src/Components/Home/Character.tsx
  src/Components/Home/CharacterModal.tsx
  src/Components/Home/SpeechBubble.tsx
  src/Components/Home/SpeechBubbleComment.tsx
  src/Components/Home/SpeechBubbleWeatherInfo.tsx
  src/Components/common/characterImgs.ts
  src/Components/common/dailyComments.ts
  src/Components/common/useCharacters.tsx
  src/Components/common/useDailyComments.tsx
Labels: ✨ Feature, 💅 Design

#59 반응형 초안
  src/App.tsx
  src/Atom/pcScreen.ts
  src/Components/Home/SpeechBubble.tsx
  src/Components/Home/SpeechBubbleComment.tsx
  src/Components/Home/SpeechBubbleWeatherInfo.tsx
  src/Components/Weekly/WeeklyForecast.tsx
  src/Components/Weekly/WeeklyItem.tsx
  src/Components/common/BottomNav.tsx
  src/Components/style/SLayout.tsx
  src/Hooks/useSetScreen.tsx
  src/index.tsx
Labels: ✨ Feature, 💅 Design, ♻️ Refactor

#66 랜딩페이지, 리다이렉션 기능 추가
  src/Components/ProtectRoute.tsx
  src/Components/Search/SearchInput.tsx
  src/Pages/Landing.tsx
  src/Pages/Login.tsx
  src/Pages/Permission.tsx
  src/Router/Router.tsx
Labels: ✨ Feature, ♻️ Refactor

#70 모달 멘트 cold, supercold, freeze 작성
  src/Components/common/dailyComments.ts
  src/Constants/weatherConfig.ts
Labels: 📄 Docs

#72 스켈레톤 디자인 추가
  src/Components/Home/HourlyForecast.tsx
  src/Components/Home/ParticulateMatter.tsx
  src/Components/Home/SpeechBubble.tsx
  src/Components/Search/CityWeatherCard.tsx
  src/Components/Skeleton/HomeSkeleton.tsx
  src/Components/Skeleton/SearchCardSkeleton.tsx
  src/Components/Skeleton/WeeklySkeleton.tsx
  src/Components/Weekly/WeeklyForecast.tsx
  src/Components/style/SSkeleton.tsx
Labels: 💅 Design

#77 input focus시 확대방지
  public/index.html
Labels: ✨ Feature

#79 메타 태그 추가
  package-lock.json
  package.json
  public/index.html
  src/Components/common/MetaTag.tsx
  src/Pages/Home.tsx
  src/Pages/Landing.tsx
  src/Pages/Login.tsx
  src/Pages/Permission.tsx
  src/Pages/Search.tsx
  src/Pages/SearchDetail.tsx
  src/Pages/Setting.tsx
  src/Pages/Weekly.tsx
  src/index.tsx
Labels: ♻️ Refactor

#82 ESLint 에러 수정
  src/API/cityNameAPI.tsx
  src/API/useOpenWeatherAPI.tsx
  src/App.tsx
  src/Components/Home/Character.tsx
  src/Components/Home/CharacterModal.tsx
  src/Components/Home/SpeechBubble.tsx
  src/Components/Search/CardWaveList.tsx
  src/Components/Search/CardWeather.tsx
  src/Components/Search/LocationConfirmModal.tsx
  src/Components/Search/SearchInput.tsx
  src/Components/Setting/SetAlarmLocation.tsx
  src/Components/Setting/TermsOfUse.tsx
  src/Components/common/BottomNav.tsx
  src/Components/common/Header.tsx
  src/Components/common/Toggle.tsx
  src/Components/common/useDailyComments.tsx
  src/Components/style/SLayout.tsx
  src/Hooks/useSearchedCites.tsx
  src/Pages/Permission.tsx
Labels: ♻️ Refactor

#83 홈화면 추가 안내 UI
  src/App.tsx
  src/Assets/menual/menu-1.png
  src/Assets/menual/menu-2.png
  src/Assets/menual/menu-3.png
  src/Components/InstallationManual.tsx
  src/Components/common/Header.tsx
  src/Components/common/PWAInstallPrompt.tsx
  src/Router/Router.tsx
Labels: ✨ Feature, 💅 Design, ♻️ Refactor

#84 aria-label 추가
  src/Components/Login/ButtonGender.tsx
  src/Components/Setting/SetProfile.tsx
  src/Components/Setting/TermsOfUse.tsx
  src/Components/common/Header.tsx
  src/Components/common/Toggle.tsx
Labels: ♻️ Refactor
