Repository haron-lee/we-wear-weather, pull requests merged in 2023-07, with the labels that each got.

#6 미세먼지, 시간대별 날씨
  src/Assets/icons-sm-weather/icon-broken-clouds.svg
  src/Assets/icons-sm-weather/icon-clear-sky.svg
  src/Assets/icons-sm-weather/icon-few-clouds.svg
  src/Assets/icons-sm-weather/icon-mist.svg
  src/Assets/icons-sm-weather/icon-rainy-thunder.svg
  src/Assets/icons-sm-weather/icon-rainy.svg
  src/Assets/icons-sm-weather/icon-scattered-clouds.svg
  src/Assets/icons-sm-weather/icon-shower-rainy.svg
  src/Assets/icons-sm-weather/icon-snow.svg
  src/Assets/particulate-matter-bad.svg
  src/Assets/particulate-matter-good.svg
  src/Assets/particulate-matter-soso.svg
  src/Components/Home/HomeTest.tsx
  src/Components/Home/HourlyForcast.tsx
  src/Components/Home/ParticulateMatter.tsx
  src/GlobalStyle.tsx
  src/Pages/Home.tsx
Labels: 💅 Design

#7 홈페이지 캐릭터, 캐릭터 모달
  src/Assets/char-male.png
  src/Assets/touch-pointer.svg
  src/Components/Home/Character.tsx
  src/Components/Home/CharacterModal.tsx
  src/Components/Home/HourlyForecast.tsx
  src/Components/Home/ParticulateMatter.tsx
  src/Components/common/Button.tsx
  src/Pages/Home.tsx
  src/Pages/Login.tsx
Labels: 🛠️ Feature, 💅 Design

#9 메인페이지 말풍선 마크업
  src/Assets/icon-location.svg
  src/Assets/speech-bubble-tail.svg
  src/Assets/speech-bubble.svg
  src/Assets/weather-broken-clouds.svg
  src/Assets/weather-clear.svg
  src/Assets/weather-few-clouds.svg
  src/Assets/weather-mist.svg
  src/Assets/weather-moon.svg
  src/Assets/weather-rain.svg
  src/Assets/weather-rainy-thunder.svg
  src/Assets/weather-scattered-clouds.svg
  src/Assets/weather-shower-rain.svg
  src/Assets/weather-snow.svg
  src/Components/Home/SpeechBubble.tsx
  src/Components/Home/SpeechBubbleWeatherInfo.tsx
  src/Pages/Home.tsx
Labels: 💅 Design

#12 검색페이지 Input 컴포넌트 구현, 자동완성 구현
  src/Components/Search/SearchInput.tsx
  src/Components/common/BottomNav.tsx
  src/Components/common/Header.tsx
  src/Pages/Search.tsx
  src/Pages/SearchDetail.tsx
  src/Router/Router.tsx
Labels: 🛠️ Feature, 💅 Design, ♻️ Refactor

#16 주간예보 UI
  .gitignore
  src/Components/Weekly/WeeklyForecast.tsx
  src/Components/Weekly/WeeklyItem.tsx
  src/Components/Weekly/WeeklyTest.tsx
  src/Components/common/smallWeatherIcons.ts
  src/Pages/Weekly.tsx
Labels: 💅 Design
